### PR TITLE
Fix #51

### LINKED ISSUE #51: r/isa crashes when encountering a network error
```
Exception in thread "main" java.net.UnknownHostException: www.reddit.com: Temporary failure in name resolution
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at net.dean.jraw.http.OkHttpNetworkAdapter.execute(OkHttpNetworkAdapter.kt:16)
        at net.dean.jraw.oauth.OAuthHelper.scriptOAuthData$lib(OAuthHelper.kt:59)
        at net.dean.jraw.oauth.OAuthHelper.automatic(OAuthHelper.kt:32)
        at net.dean.jraw.oauth.OAuthHelper.automatic$default(OAuthHelper.kt:27)
        at io.github.mojira.risa.infrastructure.RedditKt.loginToReddit(Reddit.kt:24)
        at io.github.mojira.risa.MainKt.main(Main.kt:37)
        at io.github.mojira.risa.MainKt.main(Main.kt)
```

Execution of the program stopped and didn't resume.

### PR DESCRIPTION
**Pull request by urielsalis**
#### Checklist
- [ ] Included tests
- [ ] Tested on https://reddit.com/

### CODE REVIEW

File: src/main/kotlin/io/github/mojira/risa/Main.kt [hunk 1]
```diff
@@ -22,21 +22,32 @@ import io.github.mojira.risa.infrastructure.setWebhookOfLogger
...
     val config = readConfig()
     setWebhookOfLogger(config)
 
     log.info("Starting r/isa")
     while (true) {
-        val redditCredentials = loginToReddit(config)
+        val redditCredentials = try {
+            loginToReddit(config)
+        } catch (e: Exception) {
+            log.error("Error logging to Reddit", e)
```
Comment (violine1101) [inline src/main/kotlin/io/github/mojira/risa/Main.kt:39]:
```suggestion
            log.error("Error logging in to Reddit", e)
```

File: src/main/kotlin/io/github/mojira/risa/Main.kt [hunk 2]
```diff
@@ -22,21 +22,32 @@ import io.github.mojira.risa.infrastructure.setWebhookOfLogger
...
+            TimeUnit.MINUTES.sleep(1)
+            continue
+        }
         log.info("Logged in to Reddit")
-        val jiraClient = loginToJira(config)
+        val jiraClient = try {
+            loginToJira(config)
+        } catch (e: Exception) {
+            log.error("Error logging to Jira", e)
```
Comment (violine1101) [inline src/main/kotlin/io/github/mojira/risa/Main.kt:47]:
```suggestion
            log.error("Error logging in to Jira", e)
```

**Review by violine1101 — APPROVED** [review]
